# Generated by Django 4.1.5 on 2023-01-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': ('Recurso',), 'verbose_name_plural': 'Recursos'},
        ),
    ]
